/*
* ----------------------------------------
* global types
* ----------------------------------------
*/
export const HASH_CHANGE = 'HASH_CHANGE'
export const CHANGE_DYNAMIC_COMPONENT = 'CHANGE_DYNAMIC_COMPONENT'
export const CLOSE_DYNAMIC_COMPONENT = 'CLOSE_DYNAMIC_COMPONENT'

// resource recent
export const RECENT_MODIFY_ORDER = 'RECENT_MODIFY_ORDER'
export const RECENT_ADD_ITEM = 'RECENT_ADD_ITEM'
export const RECENT_DELETE_ITEM = 'RECENT_DELETE_ITEM'
export const RECENT_SET_ACTIVE = 'RECENT_SET_ACTIVE'
export const RECENT_RECORD_MODIFICATION = 'RECENT_RECORD_MODIFICATION'
export const RECENT_REPLACE_PATH = 'RECENT_REPLACE_PATH'

// resource tree
export const LOAD_RESOURCE_TREE = 'LOAD_RESOURCE_TREE'
export const LOAD_CHILDNODES = 'LOAD_CHILDNODES'
export const TOGGLE_STATUS_RESOURCE_TREE = 'TOGGLE_STATUS_RESOURCE_TREE'

// editor
export const EDITOR_SET_FILE_TYPE = 'EDITOR_SET_FILE_TYPE'
export const EDITOR_SET_IMAGE_TYPE = 'EDITOR_SET_IMAGE_TYPE'
export const EDITOR_SET_SYSTEM_TYPE = 'EDITOR_SET_SYSTEM_TYPE'
export const EDITOR_SET_SEARCH_TYPE = 'EDITOR_SET_SEARCH_TYPE'
export const EDITOR_SET_ANCHOR = 'EDITOR_SET_ANCHOR'
export const EDITOR_SET_PROMPT_LISTS = 'EDITOR_SET_PROMPT_LISTS'
export const EDITOR_SET_PROMPT_ENGINE = 'EDITOR_SET_PROMPT_ENGINE'
export const EDITOR_CLEAN = 'EDITOR_CLEAN'

// search box
export const SEARCHBOX_SHOW = 'SEARCHBOX_SHOW'
export const SEARCHBOX_CLOSE = 'SEARCHBOX_CLOSE'

// file
export const FILE_CREATE = 'FILE_CREATE'

// toolbar
export const TOOLBAR_ADD_ITEM = 'TOOLBAR_ADD_ITEM'
export const TOOLBAR_DELETE_ITEM = 'TOOLBAR_DELETE_ITEM'

// contextmenu extension
export const EXTMENU_ADD_ITEM = 'EXTMENU_ADD_ITEM'
export const EXTMENU_DELETE_ITEM = 'EXTMENU_DELETE_ITEM'

// config
export const CONFIG_SET = 'CONFIG_SET'
